version: "3.8"

services:
  app:
    build: .
    container_name: console-api2
    restart: always
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    env_file: ./.env
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - mysql:/var/lib/mysql


volumes:
  mysql:
    external: true
