name: Clonar repositorio privado

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Clonar repositorio privado
      run: |
        git clone https://github.com/superpollo2/certs.git
      env:
        GH_TOKEN: ${{ secrets.TOKEN_GI}}
