name: Build, Deploy, and Run Docker

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
      
jobs:
  build-and-deploy:
    name: Build, Deploy, and Run Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and Run Docker Container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            cd ${{ secrets.WORK_DIR}}
            git pull
            mvn clean install
            docker stop consolea-api || true
            docker rm consolea-api || true
            docker build -t consoleapi .
            docker run --net=host -d -p 8092:8092 --name console-api consoleapi

