
name: Build, Deploy, and Run 

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-deploy-and-run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  
      uses: actions/checkout@v2
      
    - name: Clone repository
      run: |
        git clone https://${{ secrets.USER_GI}}:${{ secrets.TOKEN_GI }}@${{secrets.REPOSITORY}}
      env:
        GH_TOKEN: ${{ secrets.TOKEN_GI }}

    - name: Install OpenVPN
      run: sudo apt-get install openvpn

    - name: Move the dir to configuration openvpn 
      run: |
        sudo mv ./certs/ ${{secrets.PATH_DIR_OVPN}}

    - name: Run Openvpn
      run: sudo openvpn --config ${{secrets.PATH_DIR_OVPN}}certs/${{secrets.CERT}} &

    - name: SSH to Host
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ env.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent)"
        ssh-add ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
      
    

      
