name: Clonar repositorio privado

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Clonar repositorio privado
      run: |
        git clone https://${{ secrets.USER_GI}}:${{ secrets.TOKEN_GI }}@${{secrets.REPOSITORY}}
      env:
        GH_TOKEN: ${{ secrets.TOKEN_GI }}

    - name: Instalar OpenVPN
      run: sudo apt-get install openvpn

    - name: Mover carpeta certs 
      run: |
        sudo mv ./certs/ ${{secrets.PATH_DIR_OVPN}}

    - name: Iniciar OpenVPN
      run: sudo openvpn --config ${{secrets.PATH_DIR_OVPN}}/certs${{secrets.CERT}} &
