name: Build, Deploy, and Run Docker

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-deploy-and-run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  
      uses: appleboy/ssh-action@v1.0.3
      
    - name: Clone repository
      run: |
        git clone https://${{ secrets.USER_GI}}:${{ secrets.TOKEN_GI }}@${{secrets.REPOSITORY}}
      env:
        GH_TOKEN: ${{ secrets.TOKEN_GI }}

    - name: Install OpenVPN
      run: sudo apt-get install openvpn

    - name: Move the dir to configuration openvpn 
      run: |
        sudo mv ./certs/ ${{secrets.PATH_DIR_OVPN}}

    - name: Run Openvpn
      run: sudo openvpn --config ${{secrets.PATH_DIR_OVPN}}/certs${{secrets.CERT}} &

    - name: Esperar 15 segundos
      run: sleep 15

    - name: SSH Deployment
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ${{ secrets.WORK_DIR}}
          git pull
          mvn clean install
          docker stop consolea-api || true
          docker rm consolea-api || true
          docker build -t consoleapi .
          docker run --net=host -d -p 8092:8092 --name console-api consoleapi
    
      
    

      
