name: Build, Deploy, and Run Docker

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-deploy-and-run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar OpenVPN
        run: sudo apt-get install openvpn

      - name: Descargar archivo de configuración
        run: |
          mkdir certs
          curl -LJO -u superpollo2:${{ secrets.TOKEN_GI }} ${{ secrets.REPOSITORY }}
          mv ${{ secrets.CERT }} certs/

      - name: Esperar 15 segundos
        run: sleep 15

      - name: SSH Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ${{ secrets.WORK_DIR}}
            git pull
            mvn clean install
            docker stop consolea-api || true
            docker rm consolea-api || true
            docker build -t consoleapi .
            docker run --net=host -d -p 8092:8092 --name console-api consoleapi
